import { Injectable } from '@angular/core';

export interface FeatureSpec {
  name: string;
  description: string;
  requirements: string[];
  acceptanceCriteria?: string[];
}

export interface GeneratedFile {
  path: string;
  content: string;
  action: 'create' | 'update';
}

export interface GeneratedFeature {
  spec: FeatureSpec;
  components: Array<{ name: string; path: string }>;
  entryPoint: string;
  dependencies: string[];
}

export interface ShipResult {
  success: boolean;
  feature?: GeneratedFeature;
  files?: GeneratedFile[];
  validation?: {
    valid: boolean;
    errors: string[];
    warnings: string[];
  };
  flagName?: string;
  errors?: string[];
}

export interface ShipOptions {
  validate?: boolean;
  createFlag?: boolean;
  dryRun?: boolean;
}

export interface ComponentInfo {
  id: string;
  name: string;
  description: string;
  props: Array<{ name: string; type: string; required: boolean }>;
  source: string;
  framework: string;
}

@Injectable({
  providedIn: 'root'
})
export class ShipkitService {
  private registeredComponents: ComponentInfo[] = [];

  async ship(spec: FeatureSpec, options: ShipOptions = {}): Promise<ShipResult> {
    console.log('ShipKit: Generating feature', spec.name);
    console.log('Options:', options);

    await this.delay(500);

    const files: GeneratedFile[] = [
      {
        path: `src/features/${this.kebabCase(spec.name)}/${this.kebabCase(spec.name)}.component.ts`,
        content: this.generateComponentCode(spec),
        action: 'create'
      },
      {
        path: `src/features/${this.kebabCase(spec.name)}/${this.kebabCase(spec.name)}.component.scss`,
        content: '/* Generated styles */\n',
        action: 'create'
      },
      {
        path: `src/features/${this.kebabCase(spec.name)}/${this.kebabCase(spec.name)}.component.spec.ts`,
        content: this.generateTestCode(spec),
        action: 'create'
      },
      {
        path: `src/features/${this.kebabCase(spec.name)}/index.ts`,
        content: `export * from './${this.kebabCase(spec.name)}.component';\n`,
        action: 'create'
      }
    ];

    const feature: GeneratedFeature = {
      spec,
      components: [
        { name: spec.name, path: files[0].path }
      ],
      entryPoint: files[3].path,
      dependencies: ['@angular/core', '@angular/common']
    };

    const result: ShipResult = {
      success: true,
      feature,
      files,
      validation: options.validate ? {
        valid: true,
        errors: [],
        warnings: []
      } : undefined,
      flagName: options.createFlag ? `feature-${this.kebabCase(spec.name)}` : undefined
    };

    console.log('ShipKit: Generation complete', result);
    return result;
  }

  registerComponent(component: ComponentInfo): void {
    this.registeredComponents.push(component);
  }

  registerComponents(components: ComponentInfo[]): void {
    this.registeredComponents.push(...components);
  }

  getRegistry(): ComponentInfo[] {
    return [...this.registeredComponents];
  }

  private generateComponentCode(spec: FeatureSpec): string {
    return `import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * ${spec.description}
 *
 * Requirements:
 * ${spec.requirements.map(r => `* - ${r}`).join('\n')}
 */
@Component({
  selector: 'app-${this.kebabCase(spec.name)}',
  standalone: true,
  imports: [CommonModule],
  template: \`
    <div class="${this.kebabCase(spec.name)}">
      <h2>${spec.name}</h2>
      <p>${spec.description}</p>
    </div>
  \`,
  styleUrl: './${this.kebabCase(spec.name)}.component.scss'
})
export class ${spec.name}Component {
  // Generated by ShipKit
}
`;
  }

  private generateTestCode(spec: FeatureSpec): string {
    return `import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ${spec.name}Component } from './${this.kebabCase(spec.name)}.component';

describe('${spec.name}Component', () => {
  let component: ${spec.name}Component;
  let fixture: ComponentFixture<${spec.name}Component>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [${spec.name}Component]
    }).compileComponents();

    fixture = TestBed.createComponent(${spec.name}Component);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
`;
  }

  private kebabCase(str: string): string {
    return str
      .replace(/([a-z])([A-Z])/g, '$1-$2')
      .replace(/[\s_]+/g, '-')
      .toLowerCase();
  }

  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}
